import { ProxmoxConnection, ContainerConfig, DeploymentLog } from "../types";

export const getNextVmid = async (conn: ProxmoxConnection): Promise<number> => {
  try {
    // This is a simplified check. In a real app, we'd query /cluster/nextid
    // But due to CORS, this might fail in a browser environment without a proxy.
    // We will simulate a fetch if CORS allows, otherwise return a random high ID or throw.
    const url = `https://${conn.host}:${conn.port}/api2/json/cluster/nextid`;
    
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Authorization': `PVEAPIToken=${conn.user}!${conn.tokenName}=${conn.tokenSecret}`,
      }
    });

    if (!response.ok) {
      throw new Error(`Failed to get VMID: ${response.statusText}`);
    }

    const data = await response.json();
    return parseInt(data.data);
  } catch (e) {
    console.warn("Could not fetch next ID (likely CORS). Using fallback ID 9000.");
    return Math.floor(9000 + Math.random() * 1000);
  }
};

export const generatePctScript = (conn: ProxmoxConnection, config: ContainerConfig, vmid: number): string => {
  const features = [];
  if (config.features?.nesting) features.push('nesting=1');
  if (config.features?.keyctl) features.push('keyctl=1');
  if (config.features?.fuse) features.push('fuse=1');

  // Attempt to derive a sanitized name for the template. 
  // Proxmox naming conventions for OCI downloads can be implementation specific.
  // We provide a best-effort guess (e.g. grafana -> grafana-latest.tar.zst).
  const imageNameClean = config.image.split('/').pop() || config.image; 
  const templateFilename = `${imageNameClean}-${config.tag}.tar.zst`;

  return `#!/bin/bash
# ------------------------------------------------------------------------------
# Auto-generated by Proxmox OCI Converter
# ------------------------------------------------------------------------------
# Target Node: ${conn.node}
# VMID: ${vmid}
# Source Image: ${config.image}:${config.tag}
#
# INSTRUCTIONS:
# 1. Copy this script to your Proxmox VE host (e.g. via SSH).
# 2. Make it executable: chmod +x setup_container_${vmid}.sh
# 3. Run it: ./setup_container_${vmid}.sh
# ------------------------------------------------------------------------------

set -e

# --- Configuration ---
VMID=${vmid}
NODE="${conn.node}"
STORAGE_TEMPLATE="local"  # Storage to download the OCI Image to (must support 'vztmpl')
STORAGE_ROOTFS="${config.storage}" # Storage for the Container Root Disk
IMAGE_URL="docker://${config.image}:${config.tag}"
# Heuristic for the resulting filename. If script fails, check 'pvesh get /nodes/$NODE/storage/$STORAGE_TEMPLATE/content'
TEMPLATE_GUESS="$STORAGE_TEMPLATE:vztmpl/${templateFilename}"

# Container Settings
HOSTNAME="${config.name || `ct-${vmid}`}"
CORES=${config.cpus}
MEMORY=${config.memory}
NET_IF="${config.netInterface}"
IP="${config.ip}"
GW="${config.gateway || ''}"
DISK_SIZE="${config.diskSize}"

echo "=================================================="
echo "Proxmox OCI Container Deployment (VMID: $VMID)"
echo "=================================================="

# 1. Pull Image via API (pvesh)
echo "[Step 1] Pulling OCI Image: $IMAGE_URL"
echo "         Target Storage: $STORAGE_TEMPLATE"

# We use pvesh to trigger the OCI pull via the API, as 'pct create' doesn't support pulling directly yet.
pvesh create /nodes/$NODE/storage/$STORAGE_TEMPLATE/oci-registry-pull --url "$IMAGE_URL"

echo "         Pull request initiated..."
echo "         Waiting 15 seconds for download to process..."
sleep 15

# 2. Verify/Create Container
echo "[Step 2] Creating Container..."
echo "         Using Template (Guess): $TEMPLATE_GUESS"

ARGS=""
if [ ! -z "$GW" ]; then
  ARGS="$ARGS,gw=$GW"
fi

pct create $VMID $TEMPLATE_GUESS \\
  --hostname $HOSTNAME \\
  --cores $CORES \\
  --memory $MEMORY \\
  --swap 512 \\
  --net0 name=$NET_IF,bridge=vmbr0,ip=$IP$ARGS \\
  --rootfs $STORAGE_ROOTFS:$DISK_SIZE \\
  --unprivileged ${config.privileged ? 0 : 1} \\
  --features ${features.join(',')} \\
  --onboot 1

echo "         Container created successfully."

# 3. Mount Points
${config.volumes.map((vol, i) => `
echo "[Step 3] Setting Mount Point mp${i}..."
pct set $VMID --mp${i} ${vol.host},mp=${vol.container}
`).join('')}

# 4. Environment Variables
${Object.keys(config.env).length > 0 ? `
echo "[Step 4] Injecting Environment Variables..."
# We use direct config manipulation as typical OCI env var passing varies by implementation
cat <<EOT >> /etc/pve/lxc/$VMID.conf
${Object.entries(config.env).map(([k, v]) => `lxc.environment: ${k}=${v}`).join('\n')}
EOT
` : '# No environment variables to set.'}

# 5. Start
echo "[Step 5] Starting Container..."
pct start $VMID

echo "=================================================="
echo "Deployment Complete! Container $VMID is running."
echo "=================================================="
`;
};